apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "kube-watchdog"
  namespace: "kube-system"
  labels:
    tier: control-plane
    component: kubernetes-watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-watchdog
  template:
    metadata:
      labels:
        app: kubernetes-watchdog
    spec:
      hostNetwork: true
      containers:
      - name: "kubernetes-watchdog"
        image: "njeacr.azurecr.io/kubernetes-watchdog:v0.5"
        command: ["/usr/bin/kubernetes-watchdog", "run"]
        args: ["--kubeconfig=/etc/kubeconfig/config", "--leader-election-namespace=kube-system", "--cloud-provider=azure", "--cloud-provider-init=client-id:$(CLIENT_ID),client-password:$(CLIENT_PASSWORD),tenant-id:$(TENANT_ID)", "--logtostderr=true"]
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kube-watchdog-aadclient
              key: clientid
        - name: CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kube-watchdog-aadclient
              key: clientpassword
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: kube-watchdog-aadclient
              key: tenantid
        volumeMounts:
        - name: "kubeconfig"
          mountPath: "/etc/kubeconfig"
      volumes:
      - name: "kubeconfig"
        secret:
          secretName: "kube-watchdog"
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
      imagePullSecrets:
      - name: acr-auth
